# Generated by Django 5.2.7 on 2025-11-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='item_images/'),
        ),
    ]
